export const NAMELIST = ["Aayush Rajasekaran",
  "Alexandra Roatis",
  "Ali Sharif",
  "Aman Alam",
  "Benjamin Carroll",
  "Bryan Pastro",
  "Calvin Sribniak-Jones",
  "Dennis Guye",
  "Dipesh Pradhan",
  "Erik Iglikov",
  "Farbod Farsad",
  "Ge Zhong",
  "Geoffrey Stuart",
  "Ian Chan",
  "Jay Tseng",
  "Jeffrey Disher",
  "Jenni Zhang",
  "Jennifer Wang",
  "Karim Zeine",
  "Marcus McLaren",
  "Matthew Spoke",
  "Megan Wheeler",
  "Michael Mason",
  "Minh Tran",
  "Nicholas Nadeau",
  "Samantha Ha",
  "Samuel Pajot-Phipps",
  "Shidokht Hejazi Sepehr",
  "Yao Sun"];

